require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cidades", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cidade. As you add validations to Cidade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cidade.create! valid_attributes
      get cidades_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cidade = Cidade.create! valid_attributes
      get cidade_url(cidade)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cidade_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cidade = Cidade.create! valid_attributes
      get edit_cidade_url(cidade)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cidade" do
        expect {
          post cidades_url, params: { cidade: valid_attributes }
        }.to change(Cidade, :count).by(1)
      end

      it "redirects to the created cidade" do
        post cidades_url, params: { cidade: valid_attributes }
        expect(response).to redirect_to(cidade_url(Cidade.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cidade" do
        expect {
          post cidades_url, params: { cidade: invalid_attributes }
        }.to change(Cidade, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cidades_url, params: { cidade: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cidade" do
        cidade = Cidade.create! valid_attributes
        patch cidade_url(cidade), params: { cidade: new_attributes }
        cidade.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cidade" do
        cidade = Cidade.create! valid_attributes
        patch cidade_url(cidade), params: { cidade: new_attributes }
        cidade.reload
        expect(response).to redirect_to(cidade_url(cidade))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cidade = Cidade.create! valid_attributes
        patch cidade_url(cidade), params: { cidade: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cidade" do
      cidade = Cidade.create! valid_attributes
      expect {
        delete cidade_url(cidade)
      }.to change(Cidade, :count).by(-1)
    end

    it "redirects to the cidades list" do
      cidade = Cidade.create! valid_attributes
      delete cidade_url(cidade)
      expect(response).to redirect_to(cidades_url)
    end
  end
end
