require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/inscricoes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Inscricao. As you add validations to Inscricao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Inscricao.create! valid_attributes
      get inscricoes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      inscricao = Inscricao.create! valid_attributes
      get inscricao_url(inscricao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_inscricao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      inscricao = Inscricao.create! valid_attributes
      get edit_inscricao_url(inscricao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Inscricao" do
        expect {
          post inscricoes_url, params: { inscricao: valid_attributes }
        }.to change(Inscricao, :count).by(1)
      end

      it "redirects to the created inscricao" do
        post inscricoes_url, params: { inscricao: valid_attributes }
        expect(response).to redirect_to(inscricao_url(Inscricao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Inscricao" do
        expect {
          post inscricoes_url, params: { inscricao: invalid_attributes }
        }.to change(Inscricao, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post inscricoes_url, params: { inscricao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested inscricao" do
        inscricao = Inscricao.create! valid_attributes
        patch inscricao_url(inscricao), params: { inscricao: new_attributes }
        inscricao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the inscricao" do
        inscricao = Inscricao.create! valid_attributes
        patch inscricao_url(inscricao), params: { inscricao: new_attributes }
        inscricao.reload
        expect(response).to redirect_to(inscricao_url(inscricao))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        inscricao = Inscricao.create! valid_attributes
        patch inscricao_url(inscricao), params: { inscricao: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested inscricao" do
      inscricao = Inscricao.create! valid_attributes
      expect {
        delete inscricao_url(inscricao)
      }.to change(Inscricao, :count).by(-1)
    end

    it "redirects to the inscricoes list" do
      inscricao = Inscricao.create! valid_attributes
      delete inscricao_url(inscricao)
      expect(response).to redirect_to(inscricoes_url)
    end
  end
end
